### ISSUE TITLE
Cannot gen code with vendorDirectFulfillmentOrdersV1.json

### ISSUE THREAD

**Issue by Mike-the-one** [amzn/selling-partner-api-models#224]
```sh
Generating client code for ../models/vendor-direct-fulfillment-orders-api-model/vendorDirectFulfillmentOrdersV1.json - vendordirectfulfillmentorders
[main] INFO io.swagger.parser.Swagger20Parser - reading from ../models/vendor-direct-fulfillment-orders-api-model/vendorDirectFulfillmentOrdersV1.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from ../models/vendor-direct-fulfillment-orders-api-model/vendorDirectFulfillmentOrdersV1.json
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (StringReader); line: 1, column: 1])
 at [Source: (StringReader); line: 2787, column: 4]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:664)
        at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:486)
        at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:498)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2355)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:906)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4254)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:83)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:437)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:297)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:764)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:299)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by puppsupr** [comment]
Hi @Mike-the-one,

Are you still facing the issue ? 

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
