### ISSUE TITLE
The type defined in the template is inconsistent with the type returned by the interface

### ISSUE THREAD

**Issue by jinkun2014** [amzn/selling-partner-api-models#310]
https://github.com/amzn/selling-partner-api-models/blob/main/models/finances-api-model/financesV0.json

The type(object) defined in the template in financesV0.json, as
```
"FailedAdhocDisbursementEventList": {
      "type": "object",
     .....
}
```
but,  the type(array) returned by the interface as 
```
{
    "payload": {
        "FinancialEvents": {
            "ShipmentEventList": [
                
            ],
            "ShipmentSettleEventList": [
                
            ],
            "RefundEventList": [
                
            ],
            "GuaranteeClaimEventList": [
                
            ],
            "ChargebackEventList": [
                
            ],
            "PayWithAmazonEventList": [
                
            ],
            "ServiceProviderCreditEventList": [
                
            ],
            "RetrochargeEventList": [
                
            ],
            "RentalTransactionEventList": [
                
            ],
            "PerformanceBondRefundEventList": [
                
            ],
            "ProductAdsPaymentEventList": [
                
            ],
            "ServiceFeeEventList": [
                
            ],
            "SellerDealPaymentEventList": [
                
            ],
            "DebtRecoveryEventList": [
                
            ],
            "LoanServicingEventList": [
                
            ],
            "AdjustmentEventList": [
                
            ],
            "SAFETReimbursementEventList": [
                
            ],
            "SellerReviewEnrollmentPaymentEventList": [
                
            ],
            "FBALiquidationEventList": [
                
            ],
            "CouponPaymentEventList": [
                
            ],
            "ImagingServicesFeeEventList": [
                
            ],
            "NetworkComminglingTransactionEventList": [
                
            ],
            "AffordabilityExpenseEventList": [
                
            ],
            "AffordabilityExpenseReversalEventList": [
                
            ],
            "RemovalShipmentEventList": [
                
            ],
            "RemovalShipmentAdjustmentEventList": [
                
            ],
            "TrialShipmentEventList": [
                
            ],
            "TDSReimbursementEventList": [
                
            ],
            "AdhocDisbursementEventList": [
                
            ],
            "TaxWithholdingEventList": [
                
            ],
            "ChargeRefundEventList": [
                
            ],
            "FailedAdhocDisbursementEventList": [
                
            ],
            "ValueAddedServiceChargeEventList": [
                
            ],
            "CapacityReservationBillingEventList": [
                
            ]
        }
    }
}
```
so I get a wrong result when I run this code（Generated according to swagger-codegen）

```
ListFinancialEventsResponse response = api.listFinancialEventsByOrderId("123456798", 20, null);
```
error as
 
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 310 column 14 path $.payload.FinancialEvents.FailedAdhocDisbursementEventList

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
```

**Comment by cuizheng0520** [comment]
same error, how to fix it?

**Comment by lvjueweibaba** [comment]
how to fix it?

**Comment by jinkun2014** [comment]
you can refer to this json file

[financesV0.json](https://github.com/amzn/selling-partner-api-models/files/13223166/financesV0.json)

**Comment by lvjueweibaba** [comment]
> @lvjueweibaba you can refer to this json file
> 
> [financesV0.json](https://github.com/amzn/selling-partner-api-models/files/13223166/financesV0.json)

好的，谢谢
