### ISSUE TITLE
[BUG] Java Client Json conversion error

### ISSUE THREAD

**Issue by chxbca** [amzn/selling-partner-api-models#53]
FbaInventoryApi#getInventorySummaries

When the return lastUpdatedTime is Blank  Throw an Exception

org.threeten.bp.format.DateTimeParseException: Text '' could not be parsed at index 0
	at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1587)
	at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
	at org.threeten.bp.OffsetDateTime.parse(OffsetDateTime.java:359)
	at io.swagger.client.JSON$OffsetDateTimeTypeAdapter.read(JSON.java:215)
	at io.swagger.client.JSON$OffsetDateTimeTypeAdapter.read(JSON.java:179)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.swagger.client.JSON.deserialize(JSON.java:137)
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:739)

**Comment by smargoli2** [comment]
Still dealing with this issue with C# generated code
